apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rainap-frontend-1
  name: rainap-lb-1
  namespace: prraina
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rainap-frontend-1
  type: NodePort
status:
  loadBalancer: {}
